---
- name: Permissions for Firewalld
  firewalld: 
    port: "{{ item }}"
    permanent: true 
    state: enabled 
  loop: 
    - "3306/tcp"                    
    - "9869/tcp"
  notify: 
    - Restart Firewalld
    
- name: Install packages for MySQL 
  dnf: 
    name: "{{ packages_for_MySQL }}"
    state: latest

- name: Start and Enabled MySQL
  service:
    name: mysqld
    enabled: yes
    state: started

- name: Configurations root password for MySQL 
  mysql_user:
    check_implicit_admin: true
    login_user: "{{ mysql_login_root }}"
    login_password: "{{ mysql_root_password }}"
    user: root 
    password: "{{ mysql_root_password }}"
    host: localhost

- name: Create user 'oneadmin' by MySQL 
  community.mysql.mysql_user:
    name: "{{ mysql_user_one }}"
    password: "{{ mysql_password_one }}"
    priv: '*.*:ALL,GRANT'
    host: '%'
    state: present
    login_user: "{{ mysql_login_root }}"
    login_password: "{{ mysql_root_password }}"

#    - name: Connecting a Community Repository
#      copy: 
#        src: opennebula.repo
#        dest: "{{ path_for_opennebula_repo }}"
      
#    - name: yum makecache
#      shell: yum makecache -y 

- name: Connecting a Community Repository
  shell: |
        cat << "EOT" > /etc/yum.repos.d/opennebula.repo
        [opennebula]
        name=OpenNebula Community Edition
        baseurl=https://downloads.opennebula.io/repo/6.0/CentOS/8/$basearch
        enabled=1
        gpgkey=https://downloads.opennebula.io/repo/repo.key
        gpgcheck=1
        repo_gpgcheck=1
        EOT
        yum makecache -y

- name: Disabled SELinux 
  shell: setenforce 0  

- name: Disabled SELinux 
  ansible.posix.selinux:
    state: disabled

- name: Install epel-release 
  yum: 
    name: epel-release
    state: latest

- name: Install packages for OpenNebula
  dnf: 
    name: "{{ packages_for_OpenNebula }}"
    state: latest 

- name: Configuring the connection of Opennebula to the database
  template: 
    src: oned.conf.j2
    dest: "{{ path_for_oned_conf }}"

- name: Enabled services by OpenNebula
  service:
    name: opennebula
    enabled: yes 
    state: started
  loop:
    - opennebula
    - opennebula-sunstone
    - opennebula-gate
    - opennebula-flow