---
- name: Configurations node Front-end 
  include_tasks: front-end.yml
  when:
    - ansible_ssh_host == '192.168.0.105'

- name: Configurations node kvm
  include_tasks: node-kvm.yml
  when:
    - ansible_ssh_host == '192.168.0.106'

- name: Configurations node lxc
  include_tasks: node-lxc.yml
  when:
    - ansible_ssh_host == '192.168.0.104'